### ISSUE TITLE
traing problem with info_loss cann't call backward()

### ISSUE THREAD

**Issue by lircsszz** [AliLotfi92/InfoMaxVAE#2]
during trainning procedure, when info_loss.bacjkward() it outpout those :
 File "infomaxVAE.py", line 188, in <module>
    info_loss.backward()
  File "/usr/local/anaconda3/envs/sshape/lib/python3.7/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/anaconda3/envs/sshape/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [20, 118, 1, 1]] is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

it seems info_loss be modified elsewhere, any idea how to fix this?

**Comment by lircsszz** [comment]
finally I fixed it by install pytorch 0.4.1

**Comment by AliLotfi92** [comment]
I fixed the issue with the newer versions of Pytorch, too! Please check it.
